version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: synchro_es
    restart: always
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: synchro_es_db
    ports:
    - "3306:3306"

    cap_add:
      - SYS_NICE